# Generated by Django 4.2.5 on 2023-09-16 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tarifs",
            old_name="ptice",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="tarifs",
            old_name="ptice_old",
            new_name="price_old",
        ),
    ]
